"""initial schema - tenants billing_events analytics_results

Revision ID: a88405fec47b
Revises: 
Create Date: 2026-04-08 15:30:34.188085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a88405fec47b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('module', sa.String(), nullable=False),
    sa.Column('period_type', sa.String(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analytics_lookup', 'analytics_results', ['tenant_id', 'module', 'period_type', 'period_start'], unique=False)
    op.create_table('billing_events',
    sa.Column('invoice_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=True),
    sa.Column('practitioner_id', sa.String(), nullable=True),
    sa.Column('provider_number', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('appointment_id', sa.String(), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('service_date', sa.Date(), nullable=False),
    sa.Column('mbs_item', sa.String(), nullable=False),
    sa.Column('item_description', sa.String(), nullable=True),
    sa.Column('schedule_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('charged_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('billing_type', sa.String(), nullable=False),
    sa.Column('claim_status', sa.String(), nullable=False),
    sa.Column('payment_status', sa.String(), nullable=False),
    sa.Column('medicare_benefit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('gap_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('patient_paid', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('insurer_paid', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('dva_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_received', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('outstanding', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('claim_submitted_date', sa.Date(), nullable=True),
    sa.Column('claim_processed_date', sa.Date(), nullable=True),
    sa.Column('payment_received_date', sa.Date(), nullable=True),
    sa.Column('referring_doctor', sa.String(), nullable=True),
    sa.Column('referring_provider_no', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('invoice_id')
    )
    op.create_index('ix_billing_claim', 'billing_events', ['tenant_id', 'claim_status'], unique=False)
    op.create_index(op.f('ix_billing_events_tenant_id'), 'billing_events', ['tenant_id'], unique=False)
    op.create_index('ix_billing_mbs', 'billing_events', ['tenant_id', 'mbs_item'], unique=False)
    op.create_index('ix_billing_status', 'billing_events', ['tenant_id', 'payment_status'], unique=False)
    op.create_index('ix_billing_tenant_date', 'billing_events', ['tenant_id', 'service_date'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('practice_name', sa.String(), nullable=False),
    sa.Column('abn', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenants')
    op.drop_index('ix_billing_tenant_date', table_name='billing_events')
    op.drop_index('ix_billing_status', table_name='billing_events')
    op.drop_index('ix_billing_mbs', table_name='billing_events')
    op.drop_index(op.f('ix_billing_events_tenant_id'), table_name='billing_events')
    op.drop_index('ix_billing_claim', table_name='billing_events')
    op.drop_table('billing_events')
    op.drop_index('ix_analytics_lookup', table_name='analytics_results')
    op.drop_table('analytics_results')
    # ### end Alembic commands ###
